# Generated by Django 3.1.3 on 2020-11-25 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Handbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Наименование')),
                ('short_title', models.CharField(max_length=30, verbose_name='Короткое наименование')),
                ('description', models.TextField(verbose_name='Описание')),
                ('version', models.CharField(max_length=50, unique=True, verbose_name='Версия')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
            ],
        ),
        migrations.CreateModel(
            name='ElementHandbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Код элемента')),
                ('value', models.CharField(max_length=200, verbose_name='Значение элемента')),
                ('handbook_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handbook.handbook')),
            ],
        ),
    ]
