# Generated by Django 3.1.3 on 2020-11-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handbook',
            name='version',
            field=models.CharField(max_length=50, verbose_name='Версия'),
        ),
        migrations.AlterUniqueTogether(
            name='handbook',
            unique_together={('title', 'version')},
        ),
    ]
